echo "backup package start ... ..."
mkdir  bak
cp -rf /usr/ebank/buildit/app/BPServer/CashManage/classes/com/citic/bpserver/component/corp/ecash/trustloan/FindMenuListCmp.class bak/
cp -rf /usr/ebank/buildit/app/BPServer/CashManage/classes/com/citic/bpserver/component/corp/ecash/trustloan/FindMenuListCmp.class bak/
cp -rf /usr/ebank/buildit/app/BPServer/CashManage/classes/com/citic/bpserver/component/corp/ecash/trustloan/FindMenuListCmp.class bak/
cp -rf /usr/ebank/buildit/app/BPServer/CashManage/classes/com/citic/bpserver/component/corp/ecash/trustloan/FindMenuListCmp.class bak/
cp -rf /usr/ebank/buildit/app/BPServer/CashManage/classes/com/citic/bpserver/component/corp/ecash/trustloan/FindMenuListCmp.class bak/
cp -rf /usr/ebank/buildit/app/BPServer/CashManage/classes/com/citic/bpserver/component/corp/ecash/trustloan/FindMenuListCmp.class bak/
cp -rf /usr/ebank/buildit/app/BPServer/CashManage/classes/com/citic/bpserver/component/corp/ecash/trustloan/FindMenuListCmp.class bak/
cp -rf /usr/ebank/buildit/app/BPServer/CashManage/classes/com/citic/bpserver/component/corp/ecash/trustloan/FindMenuListCmp.class bak/
cp -rf /usr/ebank/buildit/app/BPServer/CashManage/classes/com/citic/bpserver/component/corp/ecash/trustloan/FindMenuListCmp.class bak/
cp -rf /usr/ebank/buildit/app/BPServer/CashManage/classes/com/citic/bpserver/component/corp/ecash/trustloan/FindMenuListCmp.class bak/
cp -rf /usr/ebank/buildit/app/BPServer/CashManage/classes/com/citic/bpserver/component/corp/ecash/trustloan/FindMenuListCmp.class bak/
cp -rf /usr/ebank/buildit/app/BPServer/CashManage/classes/com/citic/bpserver/component/corp/ecash/trustloan/FindMenuListCmp.class bak/
cp -rf /usr/ebank/buildit/app/BPServer/CashManage/classes/com/citic/bpserver/component/corp/ecash/trustloan/FindMenuListCmp.class bak/
cp -rf /usr/ebank/buildit/app/BPServer/CashManage/classes/com/citic/bpserver/component/corp/ecash/trustloan/FindMenuListCmp.class bak/
cp -rf /usr/ebank/buildit/app/BPServer/CashManage/classes/com/citic/bpserver/component/corp/ecash/trustloan/FindMenuListCmp.class bak/
cp -rf /usr/ebank/buildit/app/BPServer/CashManage/classes/com/citic/bpserver/component/corp/ecash/trustloan/FindMenuListCmp.class bak/
cp -rf /usr/ebank/buildit/app/BPServer/CashManage/classes/com/citic/bpserver/component/corp/ecash/trustloan/FindMenuListCmp.class bak/
cp -rf /usr/ebank/buildit/app/BPServer/CashManage/classes/com/citic/bpserver/component/corp/ecash/trustloan/FindMenuListCmp.class bak/
cp -rf /usr/ebank/buildit/app/BPServer/CashManage/classes/com/citic/bpserver/component/corp/ecash/trustloan/FindMenuListCmp.class bak/
cp -rf /usr/ebank/buildit/app/BPServer/CashManage/classes/com/citic/bpserver/component/corp/ecash/trustloan/FindMenuListCmp.class bak/
cp -rf /usr/ebank/buildit/app/BPServer/CashManage/classes/com/citic/bpserver/component/corp/ecash/trustloan/FindMenuListCmp.class bak/
cp -rf /usr/ebank/buildit/app/BPServer/CashManage/classes/com/citic/bpserver/component/corp/ecash/trustloan/FindMenuListCmp.class bak/
cp -rf /usr/ebank/buildit/app/BPServer/CashManage/config/SYSDATA/BpExchange/2103010_request.xml bak/
cp -rf /usr/ebank/buildit/app/BPServer/CashManage/config/SYSDATA/BpExchange/2103010_request.xml bak/
cp -rf /usr/ebank/buildit/app/BPServer/CashManage/config/SYSDATA/BpExchange/2103010_request.xml bak/
cp -rf /usr/ebank/buildit/app/BPServer/CashManage/config/SYSDATA/BpExchange/2103010_request.xml bak/
cp -rf /usr/ebank/buildit/app/BPServer/CashManage/config/SYSDATA/BpExchange/2103010_request.xml bak/
cp -rf /usr/ebank/buildit/app/BPServer/CashManage/config/SYSDATA/BpExchange/2103010_request.xml bak/
cp -rf /usr/ebank/buildit/app/BPServer/CashManage/config/SYSDATA/BpExchange/2103010_request.xml bak/
cp -rf /usr/ebank/buildit/app/BPServer/CashManage/config/SYSDATA/BpExchange/2103010_request.xml bak/
cp -rf /usr/ebank/buildit/app/BPServer/CashManage/config/SYSDATA/BpExchange/2103010_request.xml bak/
cp -rf /usr/ebank/buildit/app/BPServer/CashManage/config/SYSDATA/BpExchange/2103010_request.xml bak/
cp -rf /usr/ebank/buildit/app/BPServer/CashManage/config/SYSDATA/BpExchange/2103010_request.xml bak/
cp -rf /usr/ebank/buildit/app/BPServer/CashManage/config/SYSDATA/BpExchange/2103010_request.xml bak/
cp -rf /usr/ebank/buildit/app/BPServer/CashManage/config/SYSDATA/BpExchange/2103010_request.xml bak/
cp -rf /usr/ebank/buildit/app/BPServer/CashManage/config/SYSDATA/BpExchange/2103010_request.xml bak/
cp -rf /usr/ebank/buildit/app/BPServer/CashManage/config/SYSDATA/BpExchange/2103010_request.xml bak/
cp -rf /usr/ebank/buildit/app/BPServer/CashManage/config/SYSDATA/BpExchange/2103010_request.xml bak/
cp -rf /usr/ebank/buildit/app/BPServer/CashManage/config/SYSDATA/BpExchange/2103010_request.xml bak/
cp -rf /usr/ebank/buildit/app/BPServer/CashManage/config/SYSDATA/BpExchange/2103010_request.xml bak/
cp -rf /usr/ebank/buildit/app/BPServer/CashManage/classes/com/citic/bpserver/component/corp/ecash/common/dao/TrustLoanDao.class bak/
cp -rf /usr/ebank/buildit/app/BPServer/CashManage/classes/com/citic/bpserver/component/corp/ecash/common/dao/TrustLoanDao.class bak/
cp -rf /usr/ebank/buildit/app/BPServer/CashManage/classes/com/citic/bpserver/component/corp/ecash/common/dao/TrustLoanDao.class bak/
cp -rf /usr/ebank/buildit/app/BPServer/CashManage/classes/com/citic/bpserver/component/corp/ecash/common/dao/TrustLoanDao.class bak/
cp -rf /usr/ebank/buildit/app/BPServer/CashManage/classes/com/citic/bpserver/component/corp/ecash/common/dao/TrustLoanDao.class bak/
cp -rf /usr/ebank/buildit/app/BPServer/CashManage/classes/com/citic/bpserver/component/corp/ecash/common/dao/TrustLoanDao.class bak/
cp -rf /usr/ebank/buildit/app/BPServer/CashManage/classes/com/citic/bpserver/component/corp/ecash/trustloan/TrustLoanBillQryCmp.class bak/
cp -rf /usr/ebank/buildit/app/BPServer/CashManage/classes/com/citic/bpserver/component/corp/ecash/trustloan/TrustLoanBillQryCmp.class bak/
cp -rf /usr/ebank/buildit/app/BPServer/CashManage/classes/com/citic/bpserver/component/corp/ecash/trustloan/TrustLoanBillQryCmp.class bak/
cp -rf /usr/ebank/buildit/app/BPServer/CashManage/classes/com/citic/bpserver/constant/corp/ecash/HostTranConstant.class bak/
cp -rf /usr/ebank/buildit/app/BPServer/CashManage/classes/com/citic/bpserver/constant/corp/ecash/HostTranConstant.class bak/
cp -rf /usr/ebank/buildit/app/BPServer/CashManage/classes/com/citic/bpserver/constant/corp/ecash/HostTranConstant.class bak/
cp -rf /usr/ebank/buildit/app/BPServer/CashManage/classes/com/citic/bpserver/constant/corp/ecash/HostTranConstant.class bak/
cp -rf /usr/ebank/buildit/app/BPServer/CashManage/classes/com/citic/bpserver/constant/corp/ecash/HostTranConstant.class bak/
cp -rf /usr/ebank/buildit/app/BPServer/CashManage/classes/com/citic/bpserver/task/corp/ecash/impl/ElectronLoanRepaymentBiz.class bak/
cp -rf /usr/ebank/buildit/app/BPServer/CashManage/classes/com/citic/bpserver/task/corp/ecash/impl/ElectronLoanRepaymentBiz.class bak/

echo "backup package end."
